import assert from "node:assert/strict";
import test from "node:test";
import { readFileSync } from "node:fs";
import { PLOT_PALETTE, autoRange, compileExpr, niceTicks, normalizePlotDimension, normalizePlotExpression, panRange, sampleParametric, samplePlot, snapRangeToNice, zoomRange } from "../Resources/web/app/pro-canvas/plot-math.js";
import { createEmptyScene, sceneHasPlot, validateScene } from "../Resources/web/app/pro-canvas/scene.js";
import { generateTikz } from "../Resources/web/app/pro-canvas/tikz-generate.js";

const plot=()=>({id:"plot",type:"plot",at:{x:10,y:15},width:60,height:40,axis:{xmin:-5,xmax:5,ymin:null,ymax:null,axisLines:"middle",grid:"none",xlabel:"",ylabel:"",title:""},series:[{expr:"x^2",domain:null,samples:100,color:"#000000",thick:true,legend:""}],style:{}});

test("plot expressions implement pgf-compatible precedence and accept equation-style input",()=>{assert.equal(compileExpr("x^2")?.(3),9);assert.equal(compileExpr("y=x^2")?.(3),9);assert.equal(normalizePlotExpression(" f(x) = x^2 "),"x^2");assert.ok(Math.abs(compileExpr("sin(90)")?.(0)-1)<1e-12);assert.ok(Math.abs(compileExpr("sin(deg(x))")?.(Math.PI/2)-1)<1e-12);assert.equal(compileExpr("-x^2")?.(3),-9);assert.equal(compileExpr("2^3^2")?.(0),512);assert.equal(compileExpr("x++"),null);assert.equal(compileExpr("foo(x)"),null);});
test("plot sampling splits discontinuities and range helpers are stable",()=>{const fn=compileExpr("1/x");assert.ok(fn);assert.ok(samplePlot(fn,-1,1,100).length>=2);const ticks=niceTicks(-5,5);assert.ok(ticks.includes(0));const step=ticks[1]-ticks[0],fraction=step/10**Math.floor(Math.log10(step));assert.ok([1,2,2.5,5,10].includes(fraction));assert.deepEqual(autoRange([]),{min:-1,max:1});});
test("plot TikZ emits pgfplots axis, series, legend, and requirement",()=>{const scene=createEmptyScene(),object=plot();object.series[0].legend="quadratic";scene.objects.push(object);const code=generateTikz(scene).code;assert.match(code,/^% requires: \\usepackage\{pgfplots\} \\pgfplotsset\{compat=1\.18\}/);assert.match(code,/\\begin\{axis\}\[/);assert.match(code,/domain=-5:5/);assert.match(code,/samples=100/);assert.match(code,/\{x\^2\};/);assert.match(code,/\\addlegendentry\{quadratic\}/);assert.match(code,/\\end\{axis\}/);assert.doesNotMatch(code,/ymin=/);});
test("plot scene validation accepts valid plots and rejects malformed geometry or series",()=>{const scene=createEmptyScene();scene.objects.push(plot());assert.ok(validateScene(scene));const badWidth=structuredClone(scene);badWidth.objects[0].width=-1;assert.equal(validateScene(badWidth),null);const badSeries=structuredClone(scene);badSeries.objects[0].series={};assert.equal(validateScene(badSeries),null);});
test("function curve mode hides axes while preserving range and scalable placement",()=>{const scene=createEmptyScene(),object=plot();object.axis={...object.axis,xmin:-1,xmax:2,axisLines:"none"};object.series[0].expr="y=x^2";scene.objects.push(object);assert.ok(validateScene(scene));const code=generateTikz(scene).code;assert.match(code,/hide axis/);assert.match(code,/xmin=-1/);assert.match(code,/xmax=2/);assert.match(code,/domain=-1:2/);assert.match(code,/\{x\^2\}/);const source=readFileSync(new URL("../web-src/app/pro-canvas/canvas-ui.ts",import.meta.url),"utf8");assert.match(source,/\['plot',uiText\("Function", "関数"\)/);assert.match(source,/axis:\{xmin:-1,xmax:2/);assert.match(source,/handles\.forEach/);});
test("plot range gestures preserve focus and clamp width",()=>{assert.deepEqual(zoomRange(0,10,.5,.5),{min:2.5,max:7.5});assert.deepEqual(zoomRange(0,10,0,2),{min:0,max:20});assert.ok(Math.abs((zoomRange(0,10,.5,1e-20).max-zoomRange(0,10,.5,1e-20).min)-1e-6)<1e-12);assert.equal(zoomRange(0,10,.5,1e20).max-zoomRange(0,10,.5,1e20).min,1e9);assert.deepEqual(panRange(0,10,.1),{min:1,max:11});assert.equal(PLOT_PALETTE.length,6);});
test("plot dimensions accept only positive finite values",()=>{assert.equal(normalizePlotDimension("72.5",40),72.5);assert.equal(normalizePlotDimension("0",40),40);assert.equal(normalizePlotDimension("-2",40),40);assert.equal(normalizePlotDimension("nope",40),40);});
test("hidden plot series validate but are omitted from TikZ",()=>{const scene=createEmptyScene(),object=plot();object.series[0].visible=false;scene.objects.push(object);scene.symbols=[{id:"symbol",name:"PlotSymbol",objects:[structuredClone(object)]}];assert.ok(validateScene(scene));const output=generateTikz(scene).code;assert.match(output,/\\begin\{axis\}/);assert.doesNotMatch(output,/x\^2/);object.series[0].visible=true;assert.ok(validateScene(scene));delete object.series[0].visible;assert.ok(validateScene(scene));object.series[0].visible="yes";assert.equal(validateScene(scene),null);});
test("empty fn series emit axes only in TikZ while still requiring pgfplots",()=>{const scene=createEmptyScene(),object=plot();object.series[0].expr="";scene.objects.push(object);scene.symbols=[{id:"empty",name:"EmptyPlot",objects:[structuredClone(object)]}];assert.equal(sceneHasPlot(scene),true);const output=generateTikz(scene).code;assert.match(output,/\\begin\{axis\}/);assert.match(output,/\\end\{axis\}/);assert.doesNotMatch(output,/\\addplot/);assert.doesNotMatch(output,/skipped invalid series/);});
test("parametric sampling splits whenever either coordinate is non-finite",()=>{const pieces=sampleParametric(t=>1/t,t=>t,-1,1,100);assert.equal(pieces.length,2);assert.ok(pieces.every(piece=>piece.length));});
test("nice range snapping preserves nice endpoints and caps movement",()=>{const snapped=snapRangeToNice(-3.10666,-.737385);assert.deepEqual(snapped,{min:-3.1,max:-.75});assert.ok(Math.abs((snapped.max-snapped.min)-(-.737385+3.10666))<.04);assert.deepEqual(snapRangeToNice(-5,5),{min:-5,max:5});assert.equal(snapRangeToNice(.19,5.29).min,.2);});
test("all plot series kinds emit in TikZ; fn passes raw, parametric skips invalid",()=>{const scene=createEmptyScene(),object=plot();object.series=[{kind:"parametric",expr:"cos(deg(t))",expr2:"sin(deg(t))",domain:null,samples:50,color:"#000000",thick:true,legend:"circle"},{kind:"polar",expr:"1+cos(deg(t))",domain:null,samples:60,color:"#ff0000",thick:false,legend:""},{kind:"points",expr:"",points:"0,0\n1 2\nbad",domain:null,samples:10,color:"#0000ff",thick:false,legend:"dots"},{kind:"fn",expr:"x>0 ? x : -x",domain:null,samples:10,color:"#000000",thick:false,legend:"raw"},{kind:"parametric",expr:"nope(",expr2:"t",domain:null,samples:10,color:"#000000",thick:false,legend:"bad"}];scene.objects.push(object);scene.symbols=[{id:"plots",name:"Plots",objects:[structuredClone(object)]}];const output=generateTikz(scene).code;assert.match(output,/\(\{cos\(deg\(x\)\)\},\{sin\(deg\(x\)\)\}\)/);assert.match(output,/\(\{\(1\+cos\(deg\(x\)\)\)\*cos\(deg\(x\)\)\},\{\(1\+cos\(deg\(x\)\)\)\*sin\(deg\(x\)\)\}\)/);assert.match(output,/coordinates \{\(0,0\) \(1,2\)\}/);assert.match(output,/\{x>0 \? x : -x\};/);assert.match(output,/addlegendentry\{raw\}/);assert.match(output,/% skipped invalid series/);assert.doesNotMatch(output,/addlegendentry\{bad\}/);});
test("plot scene validation enforces kind-specific fields",()=>{for(const series of [{kind:"fn",expr:"x"},{kind:"parametric",expr:"t",expr2:"t^2"},{kind:"polar",expr:"1"},{kind:"points",expr:"",points:"0 0"}]){const scene=createEmptyScene(),object=plot();object.series=[{...object.series[0],...series}];scene.objects.push(object);assert.ok(validateScene(scene));}for(const series of [{kind:"unknown",expr:"x"},{kind:"parametric",expr:"t"},{kind:"points",expr:""}]){const scene=createEmptyScene(),object=plot();object.series=[{...object.series[0],...series}];scene.objects.push(object);assert.equal(validateScene(scene),null);}});
test("legend and labels are escaped or math-wrapped; axis equal emits",()=>{const scene=createEmptyScene(),object=plot();object.axis.equal=true;object.axis.xlabel="x^2 rate";object.axis.ylabel="50% & more";object.series[0].legend="y=x^2";scene.objects.push(object);const code=generateTikz(scene).code;assert.match(code,/axis equal/);assert.match(code,/xlabel=\{\$x\^2 rate\$\}/);assert.match(code,/ylabel=\{50\\% \\& more\}/);assert.match(code,/\\addlegendentry\{\$y=x\^2\$\}/);const wrapped=plot();wrapped.legend="";wrapped.series&&0;});
test("already-wrapped math legends stay untouched",()=>{const scene=createEmptyScene(),object=plot();object.series[0].legend="$y=x^2$";scene.objects.push(object);assert.match(generateTikz(scene).code,/\\addlegendentry\{\$y=x\^2\$\}/);assert.doesNotMatch(generateTikz(scene).code,/\$\$y=x/);});
