const darkThemeName = "tex64-vscode-dark-plus";
const lightThemeName = "tex64-vscode-light-plus";
const darkTokenRules = [
    { token: "comment", foreground: "6A9955" },
    { token: "keyword", foreground: "C586C0" },
    { token: "type", foreground: "4EC9B0" },
    { token: "variable", foreground: "4FC1FF" },
    { token: "string", foreground: "DCDCAA" },
    { token: "number", foreground: "B5CEA8" },
    { token: "operator", foreground: "D4D4D4" },
    { token: "delimiter", foreground: "DCDCAA" },
];
const lightTokenRules = [
    { token: "comment", foreground: "008000" },
    { token: "keyword", foreground: "AF00DB" },
    { token: "type", foreground: "267F99" },
    { token: "variable", foreground: "001080" },
    { token: "string", foreground: "795E26" },
    { token: "number", foreground: "098658" },
    { token: "operator", foreground: "1F2937" },
    { token: "delimiter", foreground: "795E26" },
];
const darkThemeColors = {
    "editor.background": "#1E1E1E",
    "editor.foreground": "#D4D4D4",
    "editorLineNumber.foreground": "#858585",
    "editorLineNumber.activeForeground": "#C6C6C6",
    "editorCursor.foreground": "#AEAFAD",
    "editor.selectionBackground": "#264F78",
    "editor.inactiveSelectionBackground": "#3A3D41",
    "editor.selectionHighlightBackground": "#ADD6FF26",
    "editor.lineHighlightBackground": "#2A2D2E",
    "editor.lineHighlightBorder": "#00000000",
    "editorIndentGuide.background": "#404040",
    "editorIndentGuide.activeBackground": "#707070",
    "editorWhitespace.foreground": "#404040",
    "editorGutter.background": "#1E1E1E",
    "editorWidget.background": "#252526",
    "editorWidget.border": "#454545",
    "editorHoverWidget.background": "#252526",
    "editorHoverWidget.border": "#454545",
    "editor.hoverHighlightBackground": "#264F7840",
    "editorSuggestWidget.background": "#252526",
    "editorSuggestWidget.border": "#454545",
    "editorSuggestWidget.foreground": "#D4D4D4",
    "editorSuggestWidget.selectedBackground": "#04395E",
    "editorSuggestWidget.highlightForeground": "#18A3FF",
    "editorBracketMatch.background": "#0064001A",
    "editorBracketMatch.border": "#888888",
    "editor.findMatchBackground": "#515C6A",
    "editor.findMatchHighlightBackground": "#EA5C0055",
    "editor.findRangeHighlightBackground": "#3A3D4166",
    "editor.wordHighlightBackground": "#575757B8",
    "editor.wordHighlightStrongBackground": "#004972B8",
    "editorError.foreground": "#F48771",
    "editorError.border": "#00000000",
    "editorOverviewRuler.border": "#00000000",
    "editorOverviewRuler.findMatchForeground": "#A0A0A0CC",
    "editorOverviewRuler.errorForeground": "#E51400CC",
    "editorMarkerNavigationError.background": "#F48771",
    "editorGutter.errorForeground": "#E51400",
    "editorWarning.foreground": "#CCA700",
    "editorOverviewRuler.background": "#00000000",
    "scrollbar.shadow": "#00000000",
    "scrollbarSlider.background": "#79797966",
    "scrollbarSlider.hoverBackground": "#646464B3",
    "scrollbarSlider.activeBackground": "#BFBFBF66",
    "editorRuler.foreground": "#5A5A5A",
};
const lightThemeColors = {
    "editor.background": "#F8FAFC",
    "editor.foreground": "#1F2937",
    "editorLineNumber.foreground": "#94A3B8",
    "editorLineNumber.activeForeground": "#334155",
    "editorCursor.foreground": "#1D4ED8",
    "editor.selectionBackground": "#BFDBFE",
    "editor.inactiveSelectionBackground": "#E5EDF6",
    "editor.selectionHighlightBackground": "#60A5FA33",
    "editor.lineHighlightBackground": "#EEF4FF",
    "editor.lineHighlightBorder": "#00000000",
    "editorIndentGuide.background": "#E2E8F0",
    "editorIndentGuide.activeBackground": "#CBD5E1",
    "editorWhitespace.foreground": "#CBD5E1",
    "editorGutter.background": "#F1F5F9",
    "editorWidget.background": "#FBFCFE",
    "editorWidget.border": "#CBD5E1",
    "editorHoverWidget.background": "#FBFCFE",
    "editorHoverWidget.border": "#CBD5E1",
    "editor.hoverHighlightBackground": "#DBEAFE",
    "editorSuggestWidget.background": "#FBFCFE",
    "editorSuggestWidget.border": "#CBD5E1",
    "editorSuggestWidget.foreground": "#1F2937",
    "editorSuggestWidget.selectedBackground": "#DBEAFE",
    "editorSuggestWidget.highlightForeground": "#1D4ED8",
    "editorBracketMatch.background": "#BBF7D01A",
    "editorBracketMatch.border": "#64748B",
    "editor.findMatchBackground": "#FDE68A",
    "editor.findMatchHighlightBackground": "#FEF3C766",
    "editor.findRangeHighlightBackground": "#E2E8F066",
    "editor.wordHighlightBackground": "#E2E8F0B8",
    "editor.wordHighlightStrongBackground": "#BFDBFEB8",
    "editorError.foreground": "#DC2626",
    "editorError.border": "#00000000",
    "editorOverviewRuler.border": "#00000000",
    "editorOverviewRuler.findMatchForeground": "#94A3B8CC",
    "editorOverviewRuler.errorForeground": "#DC2626CC",
    "editorMarkerNavigationError.background": "#DC2626",
    "editorGutter.errorForeground": "#DC2626",
    "editorWarning.foreground": "#B45309",
    "editorOverviewRuler.background": "#00000000",
    "scrollbar.shadow": "#00000000",
    "scrollbarSlider.background": "#94A3B866",
    "scrollbarSlider.hoverBackground": "#64748BB3",
    "scrollbarSlider.activeBackground": "#47556966",
    "editorRuler.foreground": "#CBD5E1",
};
export const applyMonacoTheme = (monaco, theme = "dark") => {
    var _a, _b, _c, _d, _e, _f;
    (_b = (_a = monaco.editor) === null || _a === void 0 ? void 0 : _a.defineTheme) === null || _b === void 0 ? void 0 : _b.call(_a, darkThemeName, {
        base: "vs-dark",
        inherit: true,
        rules: darkTokenRules,
        colors: darkThemeColors,
    });
    (_d = (_c = monaco.editor) === null || _c === void 0 ? void 0 : _c.defineTheme) === null || _d === void 0 ? void 0 : _d.call(_c, lightThemeName, {
        base: "vs",
        inherit: true,
        rules: lightTokenRules,
        colors: lightThemeColors,
    });
    const themeName = theme === "light" ? lightThemeName : darkThemeName;
    (_f = (_e = monaco.editor) === null || _e === void 0 ? void 0 : _e.setTheme) === null || _f === void 0 ? void 0 : _f.call(_e, themeName);
    return themeName;
};
